1. What is a Python library? Why do we use Python libraries?

In [ ]:
# python library is a collection of pre written codes which allow us to access them outside of that script 
# we can use a specific library or we can make our own library 
# __ > we use different python library to make analysis or deploy quickly . 
# like pandas library help us to create DataFrame numpy provide c array in python wich is faster then the list .
# matplotlib allow us to visualise data ...etc

2. What is the difference between Numpy array an^ List?

In [2]:
# Numpy provide array like list.WHere we can store multiple data types in list np.array able to store only one type of data . 
# another is numpy array is faster then python list. 
import numpy as np

3. Fin^ the shape, size an^ ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
# ans if 2d .
import numpy as np 
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],

[9, 10, 11, 12]])
print(a.ndim)

2


4. Write python co^e to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
a[0] # sclice array to show the 0th element that is first row 


array([1, 2, 3, 4])

5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
a[2][3] # or a[2][-1]

12

6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
a= np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [7]:
a[:,1::2] # if we consider 0th index as start start 

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [8]:
# else 
a[:,0::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [10]:
a = np.random.rand(3,3)
print(a)

[[0.0230499  0.2319143  0.71983229]
 [0.74956923 0.37786941 0.34606438]
 [0.18857697 0.31862792 0.03171573]]


8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

In [ ]:
""" np.random.rand generate a random array shape of x and y 
where np.random.randn generate a random standard normal distributed(where mean = 0 and sigma = 1 ) array """ 

9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [11]:
a= np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [12]:
a.reshape(2,6,1) # 2 = row , 6 = col , 1 new dim 

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [13]:
print(np.transpose(a))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [15]:
# or we can use T 
print(a.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


q11.



In [17]:
b=a

In [21]:
# Index wise multiplication
print(a*b)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [20]:
# matrix multiplication 
print(np.dot(a,b.T))

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [22]:
# addition 
print(a+b)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [23]:
# substraction 
print(a-b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
# division 
print(b/a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Which function in Numpy can be used to swap the byte order of an array?

In [28]:
a=np.array([1, 2, 3, 4], dtype=np.int32)

In [31]:
print(a.byteswap())

[16777216 33554432 50331648 67108864]


 What is the significance of the np.linalg.inv function?

In [ ]:
# help to solve inverse of a squred matrix 

 What ^oes the np.reshape function do, and how is it used?

In [37]:
a=np.array([[1,2,3,4],[5,5,6,7]])
# help to reshape a array 
print(a)
print(a.reshape(-1,8))

[[1 2 3 4]
 [5 5 6 7]]
[[1 2 3 4 5 5 6 7]]


What is broadcasting in Numpy?

In [38]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Add the arrays
result = a + b

In [39]:
result # here numpy brodcast B (3,0) to matcha a and return result

array([[11, 22, 33],
       [14, 25, 36]])